import dayjs from "dayjs";

export const column = [
    {
        field: "sortOrder",
        title: "序号",
        headerName: '序号',
        width: 70,
        pinned: 'left',
        editable: false,
        cellEditor: null,
    },
    {
        field: "task",
        title: "汛前任务",
        headerName: '汛前任务',
        autoHeight: true,
        wrapText: true,
        width: 150,
        pinned: 'left',
        editable: false,
        cellEditor: null,
    },
    {
        field: "taskDescription",
        title: "汛前工作要求",
        headerName: '汛前工作要求',
        autoHeight: true,
        wrapText: true,
        width: 200,
        pinned: 'left',
        editable: false,
        cellEditor: null,
    },
    {
        field: "timeLimit",
        title: "分管负责人",
        headerName: '分管负责人',
        width: 120,
        pinned: 'left',
        editable: false,
        cellEditor: null,
    },
    {
        field: "responsiblePerson",
        title: "经办人",
        headerName: '经办人',
        width: 120,
        pinned: 'left',
        editable: false,
        cellEditor: null,
    },
    {
        field: "involvedDepartments",
        title: "涉及局直单位",
        headerName: '涉及局直单位',
        width: 140,
        pinned: 'left',
        editable: false,
        cellEditor: null,
    },
    {
        field: 'sq',
        title: '水情通信处',
        headerName: '水情通信处',
        width: 200,
        editable: false,
        cellEditor: null,
        headerCellStyle: {textAlign: 'center'},
    },
    {
        field: 'hf',
        title: '合肥局',
        headerName: '合肥局',
        width: 200,
        editable: false,
        cellEditor: null,
        headerCellStyle: {textAlign: 'center'},
    }, {
        field: 'sz',
        title: '宿州局',
        headerName: '宿州局',
        width: 200,
        editable: false,
        cellEditor: null,
        headerCellStyle: {textAlign: 'center'},
    },
    {
        field: 'bb',
        title: '蚌埠局',
        headerName: '蚌埠局',
        width: 200,
        editable: false,
        cellEditor: null,
        headerCellStyle: {textAlign: 'center'},
    },
    {
        field: 'fy',
        title: '阜阳局',
        headerName: '阜阳局',
        width: 200,
        editable: false,
        cellEditor: null,
        headerCellStyle: {textAlign: 'center'},
    },
    {
        field: 'cz',
        title: '滁州局',
        headerName: '滁州局',
        width: 200,
        editable: false,
        cellEditor: null,
        headerCellStyle: {textAlign: 'center'},
    },
    {
        field: 'la',
        title: '六安局',
        headerName: '六安局',
        width: 200,
        editable: false,
        cellEditor: null,
        headerCellStyle: {textAlign: 'center'},
    },
    {
        field: 'mas',
        title: '马鞍山局',
        headerName: '马鞍山局',
        width: 200,
        editable: false,
        cellEditor: null,
        headerCellStyle: {textAlign: 'center'},
    },
    {
        field: 'wh',
        title: '芜湖局',
        headerName: '芜湖局',
        width: 200,
        editable: false,
        cellEditor: null,
        headerCellStyle: {textAlign: 'center'},
    },
    {
        field: 'hs',
        title: '黄山局',
        headerName: '黄山局',
        width: 200,
        editable: false,
        cellEditor: null,
        headerCellStyle: {textAlign: 'center'},
    }
]

