export const column =[
    {
        field: "sortOrder",
        title: "序号",
        headerName: '序号',
        width: 70,
        pinned: 'left',
        editable: false,
        cellEditor: null,
    },
    {
        field: "task",
        title: "汛前任务",
        headerName: '汛前任务',
        autoHeight: true,
        wrapText: true,
        width: 150,
        pinned: 'left',
        editable: false,
        cellEditor: null,
    },
    {
        field: "taskDescription",
        title: "任务描述",
        headerName: '任务描述',
        autoHeight: true,
        wrapText: true,
        width: 300,
        pinned: 'left',
        editable: false,
        cellEditor: null,
    },
    {
        field: "timeLimit",
        title: "时限要求",
        headerName: '时限要求',
        width: 200,
        pinned: 'left',
        editable: false,
        cellEditor: null,
    },
    {
        field: "responsiblePerson",
        title: "分管负责人",
        headerName: '分管负责人',
        width: 120,
        pinned: 'left',
        editable: false,
        cellEditor: null,
    },
    {
        field: "involvedDepartments",
        title: "涉及局直单位",
        headerName: '涉及局直单位',
        width: 120,
        pinned: 'left',
        editable: false,
        cellEditor: null,
    },
]
